import re,json
D='/home/claude/solar-system/'
jpl=json.load(open(D+'data/jpl_elements.json'))
pck=open(D+'data/pck00011.tpc').read()
def pck_vals(key):
    ms=re.findall(r'BODY%s\s*=\s*\(([^)]*)\)'%key,pck)
    v=ms[-1].replace('D','e').split()
    return [float(x) for x in v]
def pole(n):
    return {'ra':pck_vals(f'{n}_POLE_RA')[:2],'dec':pck_vals(f'{n}_POLE_DEC')[:2],'w':pck_vals(f'{n}_PM')[:2]}
ids={'Mercury':199,'Venus':299,'Earth':399,'Mars':499,'Jupiter':599,'Saturn':699,'Uranus':799,'Neptune':899,'Pluto':999,'Sun':10,'Moon':301,'Io':501,'Europa':502,'Ganymede':503,'Callisto':504,'Titan':606}
poles={k:pole(v) for k,v in ids.items()}
radii={k:pck_vals(f'{v}_RADII')[:3] for k,v in ids.items()}
# physical parameters copied from JPL phys_par page (mean radius km, mass 1e24 kg, sidereal orbital period yr, sidereal rotation d)
phys={
 'Mercury':dict(meanR=2439.4,mass=0.330103,period_y=0.2408467,rot_d=58.6462,obliq=2.11/60),
 'Venus':dict(meanR=6051.8,mass=4.86731,period_y=0.61519726,rot_d=-243.018,obliq=177.3),
 'Earth':dict(meanR=6371.0084,mass=5.97217,period_y=1.0000174,rot_d=0.99726968,obliq=23.4392911),
 'Mars':dict(meanR=3389.50,mass=0.641691,period_y=1.8808476,rot_d=1.02595676,obliq=25.19),
 'Jupiter':dict(meanR=69911,mass=1898.125,period_y=11.862615,rot_d=0.41354,obliq=3.13),
 'Saturn':dict(meanR=58232,mass=568.317,period_y=29.447498,rot_d=0.44401,obliq=26.73),
 'Uranus':dict(meanR=25362,mass=86.8099,period_y=84.016846,rot_d=-0.71833,obliq=97.77),
 'Neptune':dict(meanR=24622,mass=102.4092,period_y=164.79132,rot_d=0.67125,obliq=28.32),
 'Pluto':dict(meanR=1188.3,mass=0.0130246,period_y=247.92065,rot_d=-6.3872,obliq=None),
}
# Pluto: JPL SBDB osculating elements (epoch JD 2457588.5), two-body propagation
pl=json.load(open(D+'data/pluto_sbdb.json'))
pe={e['name']:float(e['value']) for e in pl['orbit']['elements']}
pluto=dict(epoch=float(pl['orbit']['epoch']),a=pe['a'],e=pe['e'],i=pe['i'],node=pe['om'],w=pe['w'],M0=pe['ma'],n=pe['n'])
# satellite mean elements (JPL planetary satellite mean elements page)
s=open(D+'data/sat_elem.txt').read()
def sat(name):
    i=s.find('\n '+name+' \n'); seg=[l.strip() for l in s[i:i+400].splitlines() if l.strip()][1:]
    # id, ephem, frame, epoch, then a,e,w,M,i,node,P,Pw,Pnode, then RA,Dec,tilt
    vals=[]
    for x in seg[4:]:
        try: vals.append(float(x))
        except: break
    keys=['a','e','w','M','i','node','P','Pw','Pnode','poleRA','poleDec','tilt']
    d=dict(zip(keys,vals)); d['frame']=seg[2]; return d
moons={'Moon':sat('Moon'),'Io':sat('Io'),'Europa':sat('Europa'),'Ganymede':sat('Ganymede'),'Callisto':sat('Callisto'),'Titan':sat('Titan')}
for k,v in moons.items(): print(k,v)
data=dict(table1=jpl['table1'],table2a=jpl['table2a'],table2b=jpl['table2b'],pluto=pluto,phys=phys,poles=poles,radii=radii,moons=moons)
open(D+'src/elements.gen.js','w').write('// GENERATED by data/gen_elements.py from JPL sources. Do not edit by hand.\n// Sources: JPL SSD approx_pos (Standish & Williams), JPL SBDB (Pluto), JPL planetary phys_par,\n// JPL planetary satellite mean elements, NAIF pck00011.tpc (IAU WGCCRE poles, prime meridians, radii).\nexport const DATA = '+json.dumps(data,indent=1)+';\n')
print('written')
